### PR TITLE
Add Timer component

### PR DESCRIPTION
**Pull request by anantoghosh**
Adds `<Timer />`

Timer counts down from timeLimit to 0, calls onFinish when done

**Usage:**
```js
<Timer /> // Use defaults

<Timer run={true} timeLimit={20} onFinish={() => {}} /> // Default values

```

* To stop the Timer, render with `run={false}`.
```js
<Timer run={false} />
```
 
* To restart the Timer, stop it first. *Even after the Timer has finished.*

* `timeLimit` can be set when creating <Timer /> or when restarting the Timer. *It will not change if the Timer is already running.*

* `onFinish` accepts a function to be called when timer reaches 0. *It will not execute if timer is stopped mid run.*

<hr />

**Example:**
```js
class TimerTry extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      running: true
    }
    this.currentTimeLimit = 30;
    this.onDone = this.onDone.bind(this);
  }

  render() {
    return (
    <div>
      <Timer run={this.state.running} timeLimit={this.currentTimeLimit} onFinish={this.onDone} />
      <div onClick={() => {this.setState({running: false})}} >STOP</div>
    </div>
    )
  }

  onDone() {
    // Time's up
  }
}
```

### CODE REVIEW

**Comment by anantoghosh** [comment]
Preview (looping)


"STOP" is not a part of the timer.

**Comment by skyshader** [comment]
Can we have a format of 00:00? What are your thoughts? Because a single number based countdown doesn't look like a timer.

**Comment by anantoghosh** [comment]
Yes, ok. ss:mm format right? with maximum 60s?

**Comment by skyshader** [comment]
Was thinking if minutes:seconds format.

**Comment by twishasaraiya** [comment]
Why we do we need a mm:ss format, we are going to keep only 30 seconds timer for our app???  That's what I have thought.

**Comment by Sahil-Dhawan** [comment]
Yes a 30 second timer is all thats needed to the max we can increase it to a 60 sec time , ss format is enough

**Comment by skyshader** [comment]
So, mostly it's for the look and feel of it. A timer with 00:30 would actually be clear than just writing 30. Let me know if you have better ways we can covey the timer to the user. :)

**Comment by skyshader** [comment]
Hmm keeping "30s" and counting down does make sense. Let's see who does that look in our UI.

I think we might need to tag this with a text saying "Time: 30s" to convey better. But "30s" alone seems okay.

**Comment by twishasaraiya** [comment]
I agree with @Sahil-Dhawan we could do it that way. It would look better that **Time :00:30**

**Comment by skyshader** [comment]
Awesome. Then let's merge this thing asap.

**Pull request merged**
