### PR TITLE
Module pattern

### PR DESCRIPTION
**Pull request by deveshjadon98**
Added a new `index.js` file with every component to allow developers to import components like `import SampleComponent from '../SampleComponent';` instead of  `import SampleComponent from '../SampleComponent/SampleComponent';`

This pattern allows us to make modules of the components in future.

### CODE REVIEW

**Comment by anantoghosh** [comment]
@deveshjadon98 Please do not commit package-lock.json files with this PR.

**Comment by deveshjadon98** [comment]
Adding it to gitignore

**Comment by anantoghosh** [comment]
@deveshjadon98 package-lock.json is needed in the repo, we cannot git ignore it. You just have to remove the package-lock.json files from the commits, leave gitignore as it is.
If you need help on how to do this, feel free to ask me.

**Comment by deveshjadon98** [comment]
@anantoghosh sure, i will make sure to not commit package-lock.json.

**Comment by deveshjadon98** [comment]
Changes done, please check.

**Comment by deveshjadon98** [comment]
@skyshader yes i have, i tried using SampleComponent in App it worked fine.

**Comment by skyshader** [comment]
Reverted  this since it breaks the build.
@deveshjadon98 please check once before acknowledging for future PRs.

**Pull request merged**
