### PR TITLE
Added the Landing Page

### PR DESCRIPTION
**Pull request by blenderskool**
The landing page has been created based on these designs 

**Mobile** - https://app.evrybo.com/share/project/8308/87816/IMkRaB3RydMAXNQM8rtF
**Desktop** - https://app.evrybo.com/share/project/8309/87819/HKkcT9lqXyU4Uev9JOsb

Some links to other pages have also been added. Please review the PR and let me know if any changes are required :slightly_smiling_face: 

Solves #12

### CODE REVIEW

**Comment by twishasaraiya** [comment]
@blenderskool Please make a PR to `develop` branch.Also add `quotes.svg` to **design-assests** folder.

**Comment by blenderskool** [comment]
@twishasaraiya I have changed the branch. If I move `quotes.svg` to `design-assets` then how will I import it in the page? I would get an error since it is outside the `src` folder.

**Comment by twishasaraiya** [comment]
What I meant was add the `quotes.svg` to **design-assets** folder as well. We want to keep all our icons in one place. You can keep the one currently in **Home** folder.

**Comment by blenderskool** [comment]
@twishasaraiya I have added `quotes.svg` to `design-assets` also :+1:

**Comment by twishasaraiya** [comment]
Thank you :+1: . 

Merged #81

**Pull request merged**
