### PR TITLE
Add code linting, formatting

### PR DESCRIPTION
**Pull request by anantoghosh**
Configure eslint, prettier and husky.
New packages added:
"babel-eslint"
"eslint"
"eslint-config-prettier"
"eslint-plugin-react"
"husky"
"lint-staged"
"prettier"
https://github.com/UdacityMobileWebScholarship/guess-quote/issues/15

### CODE REVIEW

**Comment by skyshader** [comment]
Have you tested this? Is it good to go?

**Comment by anantoghosh** [comment]
The setup is working. Currently only eslint:recommended rules are being checked. Should we use a stronger style guide? or just add the rules we want.

**Comment by skyshader** [comment]
Makes sense for now. :+1:

**Comment by skyshader** [comment]
Fixes #15

**Pull request merged**
